# Generated by Django 2.1.5 on 2020-02-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='img',
        ),
    ]
